### ISSUE TITLE
Create Common Framework for Amsler Test Questions

### ISSUE THREAD

**Issue by HarishKanth** [Irudayarajasekar/AmslerFinal#2]
Common Activity for Questions

**Comment by Irudayarajasekar** [comment]
what is the status?

**Comment by HarishKanth** [comment]
Not yet started. We need to discuss on this one. Ill schedule a meeting at 5:00 today.

**Comment by Irudayarajasekar** [comment]
I have another meeting between 5-5.45 today.. schedule meeting after that...
